[package]
name = "healsim"
version = "0.1.0"
authors = ["Fylwind Ruzkelt <fyl@wolfpa.ws>"]
edition = "2024"

[dependencies]
float-ord = "0.3.2"
piston_window = "0.132.0"
rand = "0.9.1"
slab = "0.4.9"
